name: unbiased_rec
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.6.10
  - click
  - cudatoolkit=10.2
  - numpy
  - pandas
  - python-dateutil
  - pickleshare
  - scikit-learn
  - pytorch=1.4
  - scipy
  - torchvision
